[{
    "user_name":"Nivetha",
    "date":ISODate("2020-10-16"),
    "attendance":"absent",
    "task_submission":"failed"
},
{
    "user_name":"Sanjith",
    "date":ISODate("2020-10-20"),
    "attendance":"absent",
    "task_submission":"failed"
},
{
    "user_name":"Monisha",
    "date":ISODate("2020-10-29"),
    "attendance":"present",
    "task_submission":"passes"
},
{
    "user_name":"Sethu",
    "date":ISODate("2020-11-01"),
    "attendance":"absent",
    "task_submission":"passed"
},
{
    "user_name":"Ram",
    "date":ISODate("2020-11-16"),
    "attendance":"present",
    "task_submission":"failed"
},
{
    "user_name":"Madhu",
    "date":ISODate("2020-11-17"),
    "attendance":"present",
    "task_submission":"passed"
}]